title: covid-19-aerosol-timeline
description: "a timeline supporting the aerosol nature of COVID-19 infection by Gary Guo"
year: 2020
author: Gary Guo and others
# add search box to navbar, true/false
search: false

#######
# Defaults 
# to simplify front matter
# all files in the "pages" folder will be output at root of site
defaults:
  - scope:
      path: "pages"
    values:
      layout: page
      permalink: /:basename:output_ext

# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
